/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 place.gltf 
Author: 3DWorkbench (https://sketchfab.com/3DWorkbench)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/layout-dragon-place-b80360833e544a2db60975e7a2c593c9
Title: layout (dragon place)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/place.gltf");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group
          position={[938.673, -0.285, -122.06]}
          rotation={[Math.PI, -0.367, Math.PI]}
        >
          <mesh
            geometry={nodes.dog_1_Mat_0.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.dog_1_Mat1_1.geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group position={[951.59, 0.241, 595.719]} rotation={[0, -1.02, 0]}>
          <mesh
            geometry={nodes.char01_extra_0.geometry}
            material={materials.extra}
          />
          <mesh
            geometry={nodes.char01_clo_0.geometry}
            material={materials.material_6}
          />
          <mesh
            geometry={nodes.char01_head_0.geometry}
            material={materials.head}
          />
        </group>
        <group position={[773.419, 55.231, -149.946]}>
          <mesh
            geometry={nodes.colorsPlus02_colorsPlus02_0.geometry}
            material={materials.colorsPlus02}
          />
          <mesh
            geometry={nodes.colorsPlus02_colorsPlus02_0_1.geometry}
            material={materials.colorsPlus02}
          />
          <mesh
            geometry={nodes.colorsPlus02_colorsPlus02_0_2.geometry}
            material={materials.colorsPlus02}
          />
          <mesh
            geometry={nodes.colorsPlus02_colorsPlus02_0_3.geometry}
            material={materials.colorsPlus02}
          />
          <mesh
            geometry={nodes.colorsPlus02_colorsPlus02_0_4.geometry}
            material={materials.colorsPlus02}
          />
          <mesh
            geometry={nodes.colorsPlus02_colorsPlus02_0_5.geometry}
            material={materials.colorsPlus02}
          />
          <mesh
            geometry={nodes.colorsPlus02_colorsPlus02_0_6.geometry}
            material={materials.colorsPlus02}
          />
        </group>
        <mesh
          geometry={nodes.rabit_1_rabit_0.geometry}
          material={materials.rabit}
          position={[75.594, 82.098, 672.69]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes.char03_woman_0.geometry}
          material={materials.woman}
          position={[1112.354, 0.419, -81.919]}
          rotation={[Math.PI, -1.241, Math.PI]}
        />
        <mesh
          geometry={nodes.char02_char03Tex_0.geometry}
          material={materials.char03Tex}
          position={[373.7, -7.139, -705.301]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes.sward_extra_0.geometry}
          material={materials.extra}
          position={[905.115, 50.863, 601.231]}
          rotation={[0, -1.02, 0]}
        />
        <mesh
          geometry={nodes.shield_extra_0.geometry}
          material={materials.extra}
          position={[978.35, 116.57, 576.542]}
          rotation={[0.474, -0.817, -1.387]}
        />
        <mesh
          geometry={nodes["Road_road+bird_0"].geometry}
          material={materials.roadbird}
          position={[152.761, -1.043, 48.146]}
        />
        <mesh
          geometry={nodes.extraColorP2_extraColor_0.geometry}
          material={materials.extraColor}
          position={[1022.028, 161.676, -153.272]}
        />
        <mesh
          geometry={nodes.woBB_woBB_0.geometry}
          material={materials.woBB}
          position={[227.337, 39.223, -390.103]}
        />
        <mesh
          geometry={nodes.Ground_ground_0.geometry}
          material={materials.ground}
          position={[471.83, -132.361, 108.175]}
        />
        <mesh
          geometry={nodes.extraColorP1_extraColor_p1_0.geometry}
          material={materials.extraColor_p1}
          position={[848.708, 104.707, -367.29]}
        />
        <mesh
          geometry={nodes.Dragon_platform_platform_0.geometry}
          material={materials.platform}
          position={[702.819, 15.269, 825.987]}
        />
        <mesh
          geometry={nodes.Plants_plantsTex_0.geometry}
          material={materials.plantsTex}
          position={[489.629, 43.261, 109.088]}
        />
        <mesh
          geometry={nodes.KolP1_wt001_0.geometry}
          material={materials.wt001}
          position={[551.599, 26.117, -837.438]}
        />
        <mesh
          geometry={nodes.addObj_uvSet02_objSet02_0.geometry}
          material={materials.objSet02}
          position={[230.802, 118.846, -96.03]}
        />
        <mesh
          geometry={nodes.water01_water01_0.geometry}
          material={materials.water01}
          position={[629.439, -28.554, 167.795]}
        />
        <mesh
          geometry={nodes.water02_water02_0.geometry}
          material={materials.water02}
          position={[587.959, 2.429, -893.424]}
        />
        <mesh
          geometry={nodes.Dragon_cDragon_0.geometry}
          material={materials.cDragon}
          position={[705.966, 281.731, 845.714]}
        />
        <mesh
          geometry={nodes.bird02_1_bird_0.geometry}
          material={materials.bird}
          position={[667.93, 436.618, 571.261]}
          rotation={[3.037, 0.014, 3.011]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/place.gltf");
